project:
  type: book

book:
  title: "Customer segmentation"
  author: "Norah Jones"
  date: "07/08/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



